app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path('', views.index, name='index'),  # 主页
    path('shop', views.shop, name='shop'), # 商城
    path('detail/<int:goodsid>', views.good_dearil, name='goodderail'),  # 商品详情
    path('cart', views.shop_cart, name='cart'),  # 购物车页面
    path('place_order', views.place_order, name='place_order'),  # 提交订单页面
    path('user_center_info', views.user_center_info),  # 用户信息页面
    path('user_center_order', views.user_center_order),  # 也用户订单
    path('user_center_site', views.user_center_site),  # 用户地址
    path('set_default_addr', views.set_default_addr),  # 用户地址
    path('login', views.acc_login),  # 登陆
    path('register', views.acc_register),  # 注册
    path('logout', views.acc_logout), #注销
    path('add_cart', views.add_cart), # 添加购物车
    path('remove_cart', views.remove_cart), # 删除购物车商品
    path('pay', views.pay), # 删除购物车商品
    path('receiving', views.receiving), # 删除购物车商品

]

honey_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('', include(('app.urls', 'app'), namespace='home')),
]

app/models.py
from django.db import models
from DjangoUeditor.models import UEditorField
from django.contrib.auth.models import User


# Create your models piphere.

class Goods(models.Model):
    """商品信息表"""
    status_choices = (
        (0, '下线'),
        (1, '上线'),
    )

    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=256, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')

    variety = models.CharField(max_length=20, verbose_name='品种')
    manufacturing_season = models.CharField(max_length=20, verbose_name='季节')
    address = models.CharField(max_length=64, verbose_name='产地')

    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.SmallIntegerField(default=1, choices=status_choices, verbose_name='商品状态')
    detail = UEditorField(width=600, height=300, toolbars="full", imagePath="images/",
                          filePath="files/", upload_settings={"imageMaxSize": 1204000}, settings={},
                          verbose_name='商品详情')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'goods'
        verbose_name = '商品信息'
        verbose_name_plural = verbose_name


class UserAddress(models.Model):
    """用户地址类"""
    user = models.ForeignKey(User, verbose_name='所属账户', on_delete=models.CASCADE)
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')

    class Meta:
        db_table = 'user_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name


class OrderInfo(models.Model):
    """用户订单信息类"""
    PAY_METHODS = {
        '1': "货到付款",
        '2': "微信支付",
        '3': "支付宝",
        '4': '银联支付'
    }

    PAY_METHODS_ENUM = {
        "CASH": 1,
        "ALIPAY": 2
    }

    ORDER_STATUS_ENUM = {
        "UNPAID": 1,
        "UNSEND": 2,
        "UNRECEIVED": 3,
        "UNCOMMENT": 4,
        "FINISHED": 5
    }

    PAY_METHOD_CHOICES = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝'),
        (4, '银联支付')
    )

    # ORDER_STATUS = {
    #     1: '待支付',
    #     2: '待发货',
    #     3: '待收货',
    #     4: '待评价',
    #     5: '已完成'
    # }

    ORDER_STATUS_CHOICES = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '已完成')
    )

    order_id = models.CharField(max_length=128, primary_key=True, verbose_name='订单id')
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    addr = models.ForeignKey('UserAddress', verbose_name='地址', on_delete=models.CASCADE)
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=3, verbose_name='支付方式')
    total_count = models.IntegerField(default=1, verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品总价')
    transit_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='订单运费')
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name='订单状态')
    trade_no = models.CharField(max_length=128, default='', verbose_name='支付编号')
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name


class OrderGoods(models.Model):
    """用户订单商品类"""
    order = models.ForeignKey('OrderInfo', verbose_name='订单', on_delete=models.CASCADE)
    sku = models.ForeignKey('Goods', verbose_name='商品', on_delete=models.CASCADE)
    count = models.IntegerField(default=1, verbose_name='商品数目')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    comment = models.CharField(max_length=256, default='', verbose_name='评论')

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name


# 购物车
class ShopCart(models.Model):
    """购物车"""
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    good = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    good_count = models.IntegerField(verbose_name='商品数量')

    def __str__(self):
        return self.good.name

    class Meta:
        db_table = 'shop_cart'
        verbose_name = '购物车'
        verbose_name_plural = verbose_name

templates/app/detail.html
{% extends 'base.html' %}
{% block title %}
    爱蜜蜂-商品详情
{% endblock title %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/css/main.css">
{% endblock style %}

{% block body %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                <div class="login_info fl">
                    欢迎您：<em><a href="/user_center_info">{{ request.user.first_name }}</a></em>
                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="/static/images/logo2.png"></a>
        <div class="search_con fl">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
        <div class="guest_cart fr">
            <a href="/cart" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>首页</h1>
            </div>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">爱蜜蜂</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="/static/media/{{ good_obj.image }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ good_obj.name }}</h3>
            <p>{{ good_obj.desc }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ good_obj.price }}</em></span>
                <span class="show_unit">单  位：{{ good_obj.unite }}</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1" id="good_count" onchange="changeGoodCount()">
                    <a href="javascript:;" class="add fr" onclick="addGoodCount()">+</a>
                    <a href="javascript:;" class="minus fr" onclick="subGoodCount()">-</a>
                </div>
            </div>
            <div class="total">总价：<em>{{ good_obj.price }}元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn" onclick="submitOrder({{ good_obj.id }})">立即购买</a>
                <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
            </ul>

            <div class="tab_content">
                {{ good_obj.detail|safe }}
            </div>

        </div>
    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2019 爱蜜蜂 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
    <div class="add_jump"></div>
{% endblock body %}

{% block script %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        var good_count = 1;  // 商品数量

        var car_count = {{ cart_count }};

        $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'})
        $('#add_cart').click(function () {
            $.ajax({
                url: '/add_cart',
                type: 'POST',
                data: {GoodID: {{ good_obj.id }}, GoodCount: good_count},
                dataType: 'JSON',
                success: function (data) {
                    if (data.status) {
                        $(".add_jump").stop().animate({
                                'left': $to_y + 7,
                                'top': $to_x + 7
                            },
                            "fast", function () {
                                $(".add_jump").fadeOut('fast', function () {
                                    if(data.new){
                                        var cc = parseInt($('#show_count').html());
                                        $('#show_count').html(cc + 1)
                                    }

                                });

                            });
                    }

                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert('服务器出错')
                }
            })


        });


        function addGoodCount() {
            good_count += 1;
            $('#good_count').val(good_count)
        }

        function subGoodCount() {
            if (good_count === 1) return
            good_count -= 1;
            $('#good_count').val(good_count)
        }

        function changeGoodCount() {
            good_count = Number($('#good_count').val())
        }
        function submitOrder(goodID) {
            window.location = '/place_order?order=' + goodID + '-' + good_count
        }
    </script>
{% endblock script %}
</body>
</html>

templates/app/login.html
{% extends 'base.html' %}
{% block title %}爱蜜蜂-登陆{% endblock title %}
{% block style %}
	<link rel="stylesheet" type="text/css" href="/static/css/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/css/main.css">
{% endblock style %}

{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo2.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/register">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 爱蜜蜂 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
{% endblock body %}

templates/app/register.html
{% extends 'base.html' %}

{% block title %}爱蜜蜂-注册{% endblock title %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="/static/css/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>

{% endblock style %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo2.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/login">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" id="reg_form">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="user_name" required>
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="password1" id="pwd" required>
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="password2" id="cpwd" required>
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>姓名:</label>
						<input type="text" name="firstname" id="name" required>
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”爱蜜蜂使用协议“</label>
						<span class="error_tip2">{{ erro }}</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2019 爱蜜蜂 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
{% endblock body %}

templates/app/shop_list.html
{% extends 'base.html' %}

{% load tags %}

{% block title %}爱蜂蜜-商城{% endblock title %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/css/main.css">
{% endblock style %}
{% block body %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到爱蜜蜂!</div>
            <div class="fr">
                {% if request.user.is_authenticated %}
                    <div class="login_info fl">
                        欢迎您：<em><a href="/user_center_info">{{ request.user.first_name }}</a></em>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="/login">登录</a>
                    </div>
                {% endif %}


            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="/" class="logo fl"><img src="/static/images/logo2.png"></a>
        <div class="search_con fl">
            <form method="get">
                <input type="text" class="input_text fl" name="search" placeholder="搜索商品"
                       value="{{ request.GET.search }}">
                <input type="submit" class="input_btn fr" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="/cart" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl">{{ request.user.shopcart_set.count }}</div>
        </div>
    </div>

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>首页</h1>
                <span></span>
            </div>

        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">爱蜂蜜</a>
        <span>></span>
        <a href="#">商城</a>
    </div>

    <div class="main_wrap clearfix">

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a>品种</a>

                <a {% if not request.GET.variety %} class="active" {% endif %}
                                                    href="?variety{% filter_handel filter_dict 'variety' %}">
                    不限
                </a>

                {% for v in variety %}
                    <a href="?variety={{ v }}{% filter_handel filter_dict 'variety' %}"
                            {% if request.GET.variety == v %}
                       class="active" {% endif %} >{{ v }}</a>
                {% endfor %}
            </div>

            <div class="sort_bar">
                <a>季节</a>
                <a {% if not request.GET.manufacturing_season %} class="active" {% endif %}
                                                                 href="?manufacturing_season{% filter_handel filter_dict 'manufacturing_season' %}">不限</a>
                {% for v in manufacturing_season %}
                    <a href="?manufacturing_season={{ v }}{% filter_handel filter_dict 'manufacturing_season' %}"
                       {% if request.GET.manufacturing_season == v %}class="active" {% endif %}>
                        {{ v }}
                    </a>
                {% endfor %}

            </div>
            <div class="sort_bar">
                <a>地区</a>
                <a {% if not request.GET.address %} class="active" {% endif %} href="?address{% filter_handel filter_dict 'address' %}">不限</a>
                {% for v in address %}
                    <a href="?address={{ v }}{% filter_handel filter_dict 'address' %}" {% if request.GET.address == v %} class="active" {% endif %} >{{ v }}</a>
                {% endfor %}
            </div>

            <ul class="goods_type_list clearfix">
                {% for good in goods_obj %}
                    <li>
                        <a href="/detail/{{ good.id }}"><img src="/static/media/{{ good.image }}"></a>
                        <h4><a href="/detail/{{ good.id }}">{{ good.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ good.price }}</span>
                            <span class="unit">{{ good.price }}/{{ good.unite }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagenation">
                {% if goods_obj.paginator.num_pages > 1 %}
                    {% if goods_obj.has_previous %}
                        <a href="?page={{ goods_obj.previous_page_number }}{% filter_handel filter_dict 'a' %}">
                            上一页
                        </a>
                    {% else %}
                        <a>
                            上一页
                        </a>
                    {% endif %}

                    {% for i in goods_obj.paginator.pager_num_range %}
                        {% if i == goods_obj.number %}
                            <a href="?page={{ i }}{% filter_handel filter_dict 'a' %}" class="active">{{ i }}</a>
                        {% else %}
                            <a href="?page={{ i }}{% filter_handel filter_dict 'a' %}">{{ i }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if goods_obj.has_next %}

                        <a href="?page={{ goods_obj.next_page_number }}{% filter_handel filter_dict 'a' %}">下一页></a>

                    {% else %}
                        <a>下一页></a>
                    {% endif %}

                {% endif %}
            </div>

        </div>

    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 爱蜂蜜 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
{% endblock body %}

templates/app/user_center_order.html
{% extends 'base.html' %}

{% block title %}用户订单页面{% endblock title %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="/static/css/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/css/main.css">
{% endblock style %}

{% block body %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到爱蜜蜂!</div>
            <div class="fr">
                <div class="login_info fl">
                    欢迎您：<em>{{ request.user.first_name }}</em>
                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="/" class="logo fl"><img src="/static/images/logo2.png"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="search_con fr">
            <form action="/shop" method="get">
                <input type="text" class="input_text fl" name="search" placeholder="搜索商品" >
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
    </div>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/user_center_info">· 个人信息</a></li>
                <li><a href="/user_center_order" class="active">· 全部订单</a></li>
                <li><a href="/user_center_site">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in order_obj %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_datetime|date:"Y-m-d H:i:s" }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>

                    <li class="col02 stress">{{ order.get_order_status_display }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for good in order.ordergoods_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="/static/media/{{ good.sku.image }}"></li>
                                    <li class="col02">{{ good.sku.name }}<em>{{ good.sku.price }}元/{{ good.sku.unite }}g</em>
                                    </li>
                                    <li class="col03">{{ good.count }}</li>
                                    <li class="col04">{{ good.price }}元</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_price }}元</td>
                        {% if order.order_status == 1 %}
                            <td width="15%">待付款</td>
                            <td width="15%"><a class="oper_btn" onclick="pay('{{ order.order_id }}')">去付款</a></td>
                        {% elif order.order_status == 2 %}
                            <td width="15%">已发货</td>
                            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                        {% elif order.order_status == 3 %}
                            <td width="15%">待收货</td>
                            <td width="15%"><a href="#" class="oper_btn" onclick="receiving('{{ order.order_id }}')">确认收货</a></td>
                        {% elif order.order_status == 4 %}
                            <td width="15%">已完成</td>
                            <td width="15%">已完成</td>
                        {% endif %}

                    </tr>
                    </tbody>
                </table>
            {% endfor %}


            {#            <div class="pagenation">#}
            {#                <a href="#">#}
            {#                    <上一页#}
            {#                </a>#}
            {#                <a href="#" class="active">1</a>#}
            {#                <a href="#">2</a>#}
            {#                <a href="#">3</a>#}
            {#                <a href="#">4</a>#}
            {#                <a href="#">5</a>#}
            {#                <a href="#">下一页></a>#}
            {#            </div>#}
        </div>
    </div>

    <div class="popup_con">
        <div class="popup">
            <p id="aaa">支付成功！</p>
        </div>

        <div class="mask"></div>
    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>

{% endblock body %}

{% block script %}
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script>
        function pay(orderID) {
            $.ajax({
                url: '/pay',
                type: 'post',
                data: {orderID: orderID},
                dataType: 'JSON',
                success: function (data) {
                    if (data.status) {
                        $('.popup_con').fadeIn('fast', function () {
                            $('#aaa').html('支付成功!');
                            setTimeout(function () {
                                $('.popup_con').fadeOut('fast', function () {
                                    window.location.reload()
                                });
                            }, 3000)

                        });
                    }
                }
            })
        }

        function receiving(orderID) {
            $.ajax({
                url: '/receiving',
                type: 'post',
                data: {orderID: orderID},
                dataType: 'JSON',
                success: function (data) {
                    if (data.status) {
                        $('.popup_con').fadeIn('fast', function () {
                            $('#aaa').html('确认收货完成!');
                            setTimeout(function () {
                                $('.popup_con').fadeOut('fast', function () {
                                    window.location.reload()
                                });
                            }, 3000)

                        });
                    }
                }
            })
        }


    </script>
{% endblock %}